### ISSUE TITLE
Depth Data ScanNet

### ISSUE THREAD

**Issue by edith-langer** [DeepSceneSeg/SSMA#6]
Hi @avalada,
I'm having troubles getting good results with ScanNet data.
I read in the depth image (extracted from the sens-file with the given decoder from ScanNet), divide the values by 255 to get an 8-bit-image and apply the jet-colormap. 

Compared to the DeepScene demo you provide on your homepage, I can see two differences. 
1. the depth image looks way darker in my case (did you use some scale factor?)
2. I never see the void class. It should have the label 0, right? What is the mapping between predicted labels and classes for ScanNet?

Thanks for your help!

**Comment by avalada** [comment]
1. We first process the extracted depth data with a depth filling algorithm and then convert the resulting depth map to the jet colorspace by dividing it with a factor of 7000 followed by multiplication with 255. Any value above 255 is clipped.

2. output of model = BxHxWxN, N being (void+number of classes). The first channel will give the void class prediction. Since during training we ignore learning of the void class, our pre-trained checkpoints will not predict the void class.

**Comment by edith-langer** [comment]
I think I was mislead by the demo examples. I assumed that unlabeled is a class you can predict. But I guess it depicts just the unlabeled points in the GT?

**Comment by avalada** [comment]
We have both models and it works better if you have the unlabeled as ignore during training. Yes it depicts the unlabeled pixels in the GT.
